# File after https://github.com/jowr/jopy/blob/master/appveyor.yml, copyright predominately Jorrit Wronski
# Tell appveyor to not use msbuild
build: false

environment:
  matrix:
    - PYTHON: 3.6
    - PYTHON: 3.7
    - PYTHON: 3.8

platform:
  - x86
  - x64

init:
  - "ECHO %PYTHON%"
  - cmd: SET PATH=C:\Miniconda3\Scripts;C:\Miniconda\Scripts;%PATH%
  - cmd: conda update -yq conda
  - cmd: conda install -yq conda-env conda-build 
  - cmd: conda create -yq -n condaenv python=%PYTHON%

install:
  - cmd: activate condaenv
  - cmd: conda install -yq numpy scipy pip pytest pandas numba IPython sphinx
  - cmd: pip install pytest-cov coveralls sympy fuzzywuzzy pint pytz fluids
  
test_script:
  - cmd: py.test --cov-report html --cov=ht -m "not slow and not numba"
branches:
  only:
    - release
