# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from typing import (
    Optional,
    Union,
)


def Ft_aircooler(
    Thi: float,
    Tho: float,
    Tci: float,
    Tco: float,
    Ntp: int = ...,
    rows: int = ...
) -> float: ...


def air_cooler_noise_GPSA(tip_speed: float, power: float) -> float: ...


def air_cooler_noise_Mukherjee(tip_speed: float, power: float, fan_diameter: float, induced: bool = ...) -> float: ...


def dP_ESDU_high_fin(
    m: float,
    A_min: float,
    A_increase: float,
    flow_area_contraction_ratio: float,
    tube_diameter: float,
    pitch_parallel: float,
    pitch_normal: float,
    tube_rows: int,
    rho: float,
    mu: float
) -> float: ...


def dP_ESDU_low_fin(
    m: float,
    A_min: float,
    A_increase: float,
    flow_area_contraction_ratio: float,
    tube_diameter: float,
    fin_height: float,
    bare_length: float,
    pitch_parallel: float,
    pitch_normal: float,
    tube_rows: int,
    rho: float,
    mu: float
) -> float: ...


def h_Briggs_Young(
    m: float,
    A: float,
    A_min: float,
    A_increase: float,
    A_fin: float,
    A_tube_showing: float,
    tube_diameter: float,
    fin_diameter: float,
    fin_thickness: float,
    bare_length: float,
    rho: float,
    Cp: float,
    mu: float,
    k: float,
    k_fin: float
) -> float: ...


def h_ESDU_high_fin(
    m: float,
    A: float,
    A_min: float,
    A_increase: float,
    A_fin: float,
    A_tube_showing: float,
    tube_diameter: float,
    fin_diameter: float,
    fin_thickness: float,
    bare_length: float,
    pitch_parallel: float,
    pitch_normal: float,
    tube_rows: int,
    rho: float,
    Cp: float,
    mu: float,
    k: float,
    k_fin: float,
    Pr_wall: None = ...
) -> float: ...


def h_ESDU_low_fin(
    m: float,
    A: float,
    A_min: float,
    A_increase: float,
    A_fin: float,
    A_tube_showing: float,
    tube_diameter: float,
    fin_diameter: float,
    fin_thickness: float,
    bare_length: float,
    pitch_parallel: float,
    pitch_normal: float,
    tube_rows: int,
    rho: float,
    Cp: float,
    mu: float,
    k: float,
    k_fin: float,
    Pr_wall: Optional[float] = ...
) -> float: ...


def h_Ganguli_VDI(
    m: float,
    A: float,
    A_min: float,
    A_increase: float,
    A_fin: float,
    A_tube_showing: float,
    tube_diameter: float,
    fin_diameter: float,
    fin_thickness: float,
    bare_length: float,
    pitch_parallel: float,
    pitch_normal: float,
    tube_rows: int,
    rho: float,
    Cp: float,
    mu: float,
    k: float,
    k_fin: float
) -> float: ...

__all__: List[str]