# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from typing import (
    Dict,
    List,
    Union,
)


def R_cylinder(Di: float, Do: float, k: float, L: float) -> float: ...


def R_to_k(R: float, t: float, A: float = ...) -> float: ...


def R_value_to_k(R_value: float, SI: bool = ...) -> float: ...


def S_isothermal_pipe_eccentric_to_isothermal_pipe(D1: float, D2: float, Z: float, L: float = ...) -> float: ...


def S_isothermal_pipe_normal_to_plane(D: float, L: float) -> float: ...


def S_isothermal_pipe_to_isothermal_pipe(D1: float, D2: float, W: float, L: float = ...) -> float: ...


def S_isothermal_pipe_to_plane(D: float, Z: float, L: float = ...) -> float: ...


def S_isothermal_pipe_to_two_planes(D: float, Z: float, L: float = ...) -> float: ...


def S_isothermal_sphere_to_plane(D: float, Z: float) -> float: ...


def cylindrical_heat_transfer(
    Ti: float,
    To: float,
    hi: float,
    ho: float,
    Di: float,
    ts: List[float],
    ks: List[float]
) -> Dict[str, Union[float, List[float]]]: ...


def k_to_R(k: float, t: float, A: float = ...) -> float: ...


def k_to_R_value(k: float, SI: bool = ...) -> float: ...


def k_to_thermal_resistivity(k: float) -> float: ...


def thermal_resistivity_to_k(r: float) -> float: ...

__all__: List[str]