# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from numpy import float64


def Akers_Deans_Crosser(
    m: float,
    rhog: float,
    rhol: float,
    kl: float,
    mul: float,
    Cpl: float,
    D: float,
    x: float
) -> float: ...


def Boyko_Kruzhilin(
    m: float,
    rhog: float,
    rhol: float,
    kl: float,
    mul: float,
    Cpl: float,
    D: float,
    x: float64
) -> float64: ...


def Cavallini_Smith_Zecchin(
    m: int,
    x: float,
    D: float,
    rhol: int,
    rhog: float,
    mul: float,
    mug: float,
    kl: float,
    Cpl: int
) -> float: ...


def Nusselt_laminar(
    Tsat: float,
    Tw: float,
    rhog: float,
    rhol: float,
    kl: float,
    mul: float,
    Hvap: float,
    L: float,
    angle: float = ...
) -> float: ...


def Shah(m: int, x: float, D: float, rhol: int, mul: float, kl: float, Cpl: int, P: float, Pc: float) -> float: ...


def h_kinetic(T: int, P: float, MW: float, Hvap: int, f: int = ...) -> float: ...

__all__: List[str]