# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from typing import Union


def Akers_Deans_Crosser(
    m: float,
    rhog: float,
    rhol: float,
    kl: float,
    mul: float,
    Cpl: float,
    D: float,
    x: float
) -> float: ...


def Boyko_Kruzhilin(m: float, rhog: float, rhol: float, kl: float, mul: float, Cpl: float, D: float, x: float) -> float: ...


def Cavallini_Smith_Zecchin(
    m: float,
    x: float,
    D: float,
    rhol: float,
    rhog: float,
    mul: float,
    mug: float,
    kl: float,
    Cpl: float
) -> float: ...


def Nusselt_laminar(
    Tsat: float,
    Tw: float,
    rhog: float,
    rhol: float,
    kl: float,
    mul: float,
    Hvap: float,
    L: float,
    angle: float = ...
) -> float: ...


def Shah(
    m: float,
    x: float,
    D: float,
    rhol: float,
    mul: float,
    kl: float,
    Cpl: float,
    P: float,
    Pc: float
) -> float: ...


def h_kinetic(T: float, P: float, MW: float, Hvap: float, f: float = ...) -> float: ...

__all__: List[str]