# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from typing import Optional


def Nu_Achenbach(Re: int, Pr: float, voidage: float) -> float: ...


def Nu_KTA(Re: int, Pr: float, voidage: float) -> float: ...


def Nu_Wakao_Kagei(Re: int, Pr: float) -> float: ...


def Nu_packed_bed_Gnielinski(
    dp: float,
    voidage: float,
    vs: int,
    rho: float,
    mu: float,
    Pr: float,
    fa: Optional[int] = ...
) -> float: ...

__all__: List[str]