# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from typing import Union


def Nu_Nusselt_Rayleigh_Hollands(Pr: float, Gr: float, buoyancy: bool = ..., Rac: float = ...) -> float: ...


def Nu_Nusselt_Rayleigh_Holling_Herwig(Pr: int, Gr: float, buoyancy: bool = ...) -> float: ...


def Nu_Nusselt_Rayleigh_Probert(Pr: float, Gr: float, buoyancy: bool = ...) -> float: ...


def Nu_vertical_helical_coil_Ali(Pr: float, Gr: float) -> float: ...


def Nu_vertical_helical_coil_Prabhanjan_Rennie_Raghavan(Pr: float, Gr: float) -> float: ...


def Rac_Nusselt_Rayleigh(H: int, L: int, W: float, insulated: bool = ...) -> float: ...


def Rac_Nusselt_Rayleigh_disk(H: int, D: float, insulated: bool = ...) -> float: ...

__all__: List[str]