# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from typing import (
    Optional,
    Union,
)


def ESDU_tube_angle_correction(angle: float) -> float: ...


def ESDU_tube_row_correction(tube_rows: int, staggered: bool = ..., Re: float = ..., method: str = ...) -> float: ...


def Nu_ESDU_73031(
    Re: float,
    Pr: float,
    tube_rows: int,
    pitch_parallel: float,
    pitch_normal: float,
    Pr_wall: Optional[float] = ...,
    angle: float = ...
) -> float: ...


def Nu_Grimison_tube_bank(
    Re: float,
    Pr: float,
    Do: float,
    tube_rows: int,
    pitch_parallel: float,
    pitch_normal: float
) -> float: ...


def Nu_HEDH_tube_bank(
    Re: float,
    Pr: float,
    Do: float,
    tube_rows: int,
    pitch_parallel: float,
    pitch_normal: float
) -> float: ...


def Nu_Zukauskas_Bejan(
    Re: float,
    Pr: float,
    tube_rows: int,
    pitch_parallel: float,
    pitch_normal: float,
    Pr_wall: Optional[float] = ...
) -> float: ...


def Zukauskas_tube_row_correction(tube_rows: int, staggered: bool = ..., Re: float = ...) -> float: ...


def baffle_correction_Bell(crossflow_tube_fraction: float, method: str = ...) -> float: ...


def baffle_leakage_Bell(
    Ssb: float,
    Stb: float,
    Sm: float,
    method: str = ...
) -> float: ...


def dP_Kern(
    m: float,
    rho: float,
    mu: float,
    DShell: float,
    LSpacing: float,
    pitch: float,
    Do: float,
    NBaffles: int,
    mu_w: Optional[float] = ...
) -> float: ...


def dP_Zukauskas(Re: float, n: int, ST: float, SL: float, D: float, rho: float, Vmax: float) -> float: ...


def laminar_correction_Bell(Re: float, total_row_passes: int) -> float: ...


def load_Zukauskas_correlations() -> None: ...


def unequal_baffle_spacing_Bell(
    baffles: int,
    baffle_spacing: float,
    baffle_spacing_in: Optional[float] = ...,
    baffle_spacing_out: Optional[float] = ...,
    laminar: bool = ...
) -> float: ...

__all__: List[str]