# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from typing import (
    List,
    Optional,
)


def Nu_coil_Xin_Ebadian(Pr: float, Gr: float, horizontal: bool = ...) -> float: ...


def Nu_free_horizontal_plate(
    Pr: float,
    Gr: float,
    buoyancy: bool,
    L: Optional[float] = ...,
    W: Optional[float] = ...,
    Method: Optional[str] = ...
) -> float: ...


def Nu_free_horizontal_plate_methods(
    Pr: float,
    Gr: float,
    buoyancy: bool,
    L: Optional[float] = ...,
    W: Optional[float] = ...,
    check_ranges: bool = ...
) -> List[str]: ...


def Nu_free_vertical_plate(
    Pr: float,
    Gr: float,
    buoyancy: None = ...,
    H: Optional[float] = ...,
    W: Optional[float] = ...,
    Method: Optional[str] = ...
) -> float: ...


def Nu_free_vertical_plate_methods(
    Pr: float,
    Gr: float,
    H: Optional[float] = ...,
    W: Optional[float] = ...,
    check_ranges: bool = ...
) -> List[str]: ...


def Nu_horizontal_cylinder(Pr: float, Gr: float, Method: Optional[str] = ...) -> float: ...


def Nu_horizontal_cylinder_Churchill_Chu(Pr: float, Gr: float) -> float: ...


def Nu_horizontal_cylinder_Kuehn_Goldstein(Pr: float, Gr: float) -> float: ...


def Nu_horizontal_cylinder_Morgan(Pr: float, Gr: float) -> float: ...


def Nu_horizontal_cylinder_methods(Pr: float, Gr: float, check_ranges: bool = ...) -> List[str]: ...


def Nu_horizontal_plate_McAdams(Pr: float, Gr: float, buoyancy: bool = ...) -> float: ...


def Nu_horizontal_plate_Rohsenow(Pr: float, Gr: float, buoyancy: bool = ...) -> float: ...


def Nu_horizontal_plate_VDI(Pr: float, Gr: float, buoyancy: bool = ...) -> float: ...


def Nu_sphere_Churchill(Pr: float, Gr: float) -> float: ...


def Nu_vertical_cylinder(
    Pr: float,
    Gr: float,
    L: Optional[float] = ...,
    D: Optional[float] = ...,
    Method: Optional[str] = ...
) -> float: ...


def Nu_vertical_cylinder_Al_Arabi_Khamis(Pr: float, Gr: float, L: float, D: float, turbulent: None = ...) -> float: ...


def Nu_vertical_cylinder_Carne_Morgan(Pr: float, Gr: float, turbulent: Optional[bool] = ...) -> float: ...


def Nu_vertical_cylinder_Eigenson_Morgan(Pr: float, Gr: float, turbulent: None = ...) -> float: ...


def Nu_vertical_cylinder_Griffiths_Davis_Morgan(Pr: float, Gr: float, turbulent: Optional[bool] = ...) -> float: ...


def Nu_vertical_cylinder_Hanesian_Kalish_Morgan(Pr: float, Gr: float) -> float: ...


def Nu_vertical_cylinder_Jakob_Linke_Morgan(Pr: float, Gr: float, turbulent: Optional[bool] = ...) -> float: ...


def Nu_vertical_cylinder_Kreith_Eckert(Pr: float, Gr: float, turbulent: Optional[bool] = ...) -> float: ...


def Nu_vertical_cylinder_McAdams_Weiss_Saunders(Pr: float, Gr: float, turbulent: Optional[bool] = ...) -> float: ...


def Nu_vertical_cylinder_Popiel_Churchill(Pr: float, Gr: float, L: float, D: float) -> float: ...


def Nu_vertical_cylinder_Touloukian_Morgan(Pr: float, Gr: float, turbulent: Optional[bool] = ...) -> float: ...


def Nu_vertical_cylinder_methods(
    Pr: float,
    Gr: float,
    L: Optional[float] = ...,
    D: Optional[float] = ...,
    check_ranges: bool = ...
) -> List[str]: ...


def Nu_vertical_plate_Churchill(Pr: float, Gr: float) -> float: ...

__all__: List[str]