# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from typing import Optional


def Aggour(
    m: float,
    x: float,
    alpha: float,
    D: float,
    rhol: float,
    Cpl: float,
    kl: float,
    mu_b: float,
    mu_w: Optional[float] = ...,
    L: Optional[float] = ...,
    turbulent: None = ...
) -> float: ...


def Davis_David(m: float, x: float, D: float, rhol: float, rhog: float, Cpl: float, kl: float, mul: float) -> float: ...


def Elamvaluthi_Srinivas(
    m: float,
    x: float,
    D: float,
    rhol: float,
    rhog: float,
    Cpl: float,
    kl: float,
    mug: float,
    mu_b: float,
    mu_w: Optional[float] = ...
) -> float: ...


def Groothuis_Hendal(
    m: float,
    x: float,
    D: float,
    rhol: float,
    rhog: float,
    Cpl: float,
    kl: float,
    mug: float,
    mu_b: float,
    mu_w: Optional[float] = ...,
    water: bool = ...
) -> float: ...


def Hughmark(
    m: float,
    x: float,
    alpha: float,
    D: float,
    L: float,
    Cpl: float,
    kl: float,
    mu_b: Optional[float] = ...,
    mu_w: Optional[float] = ...
) -> float: ...


def Knott(
    m: float,
    x: float,
    D: float,
    rhol: int,
    rhog: float,
    Cpl: Optional[float] = ...,
    kl: Optional[float] = ...,
    mu_b: Optional[float] = ...,
    mu_w: Optional[float] = ...,
    L: Optional[float] = ...,
    hl: None = ...
) -> float: ...


def Kudirka_Grosh_McFadden(
    m: float,
    x: float,
    D: float,
    rhol: float,
    rhog: float,
    Cpl: float,
    kl: float,
    mug: float,
    mu_b: float,
    mu_w: Optional[float] = ...
) -> float: ...


def Martin_Sims(
    m: float,
    x: float,
    D: float,
    rhol: float,
    rhog: float,
    hl: Optional[float] = ...,
    Cpl: Optional[float] = ...,
    kl: Optional[float] = ...,
    mu_b: Optional[float] = ...,
    mu_w: Optional[float] = ...,
    L: Optional[float] = ...
) -> float: ...


def Ravipudi_Godbold(
    m: float,
    x: float,
    D: float,
    rhol: float,
    rhog: float,
    Cpl: float,
    kl: float,
    mug: float,
    mu_b: float,
    mu_w: Optional[float] = ...
) -> float: ...


def h_two_phase(
    m: float,
    x: float,
    D: float,
    Cpl: float,
    kl: float,
    rhol: Optional[float] = ...,
    rhog: None = ...,
    mul: None = ...,
    mu_b: Optional[float] = ...,
    mu_w: Optional[float] = ...,
    mug: None = ...,
    L: Optional[float] = ...,
    alpha: Optional[float] = ...,
    method: Optional[str] = ...
) -> float: ...

__all__: List[str]