# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from typing import (
    Optional,
    Union,
)


def Nu_Nusselt_Rayleigh_Hollands(Pr: float, Gr: float, buoyancy: bool = ..., Rac: float = ...) -> float: ...


def Nu_Nusselt_Rayleigh_Holling_Herwig(Pr: float, Gr: float, buoyancy: bool = ...) -> float: ...


def Nu_Nusselt_Rayleigh_Holling_Herwig_err(Nu: float, Ra: float, Ra_third: float, D2: float) -> float: ...


def Nu_Nusselt_Rayleigh_Probert(Pr: float, Gr: float, buoyancy: bool = ...) -> float: ...


def Nu_Nusselt_vertical_Thess(Pr: float, Gr: float, H: Optional[int] = ..., L: Optional[int] = ...) -> float: ...


def Nu_vertical_helical_coil_Ali(Pr: float, Gr: float) -> float: ...


def Nu_vertical_helical_coil_Prabhanjan_Rennie_Raghavan(Pr: float, Gr: float) -> float: ...


def Rac_Nusselt_Rayleigh(
    H: float,
    L: float,
    W: float,
    insulated: bool = ...
) -> float: ...


def Rac_Nusselt_Rayleigh_disk(H: float, D: float, insulated: bool = ...) -> float: ...

__all__: List[str]