# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from typing import (
    Optional,
    Union,
)


def LMTD(
    Thi: float,
    Tho: float,
    Tci: float,
    Tco: float,
    counterflow: bool = ...
) -> float: ...


def fin_efficiency_Kern_Kraus(
    Do: float,
    D_fin: float,
    t_fin: float,
    k_fin: float,
    h: float
) -> float: ...


def is_heating_property(prop: float, prop_wall: float) -> bool: ...


def is_heating_temperature(T: int, T_wall: int) -> bool: ...


def wall_factor(
    mu: Optional[int] = ...,
    mu_wall: Optional[int] = ...,
    Pr: Optional[float] = ...,
    Pr_wall: Optional[float] = ...,
    T: Optional[int] = ...,
    T_wall: Optional[int] = ...,
    mu_heating_coeff: float = ...,
    mu_cooling_coeff: float = ...,
    Pr_heating_coeff: float = ...,
    Pr_cooling_coeff: float = ...,
    T_heating_coeff: float = ...,
    T_cooling_coeff: float = ...,
    property_option: str = ...
) -> float: ...

__all__: List[str]