# DO NOT EDIT - AUTOMATICALLY GENERATED BY tests/make_test_stubs.py!
from typing import List
from typing import Union


def blackbody_spectral_radiance(T: float, wavelength: float) -> float: ...


def grey_transmittance(extinction_coefficient: float, molar_density: int, length: float, base: float = ...) -> float: ...


def q_rad(emissivity: float, T: int, T2: float = ...) -> float: ...

__all__: List[str]